### ISSUE TITLE
lto commands not working

### ISSUE THREAD

**Issue by edcoding** [ltonetwork/lto-cli#21]
if you type lto accounts create it creates new account and then
lto accounts list it appears the following messsage...
"lto: error: No account found for L network, type 'lto accounts --help' for instructions"

**Comment by AndreaScorza** [comment]
cannot reproduce

**Comment by jasny** [comment]
Please remove the .lto directory in your home directory and/or the T and L directory in your current work directory. Update lto-cli and try again.

After removing the directory, you have to create/seed the account against.

If it still doesn't work, please copy/paste every command (redact the seed phrase) and terminal output and add it as comment here.

Please copy/paste from the terminal (as text), don't add photos of your screen.
