### ISSUE TITLE
Accept any combination of seperator chars when reading masstransfer input

### ISSUE THREAD

**Issue by jasny** [ltonetwork/lto-cli#8]
Currently a double colon is required as separator between the address and amount. Instead, allow any combination of these chars: `;`, `:`, `=`, `,` space, and tab.

```
3N6MFpSbbzTozDcfkTUT5zZ2sNbJKFyRtRj:1000000000
3N6MFpSbbzTozDcfkTUT5zZ2sNbJKFyRtRj 1000000000
3N6MFpSbbzTozDcfkTUT5zZ2sNbJKFyRtRj=1000000000
3N6MFpSbbzTozDcfkTUT5zZ2sNbJKFyRtRj  = 1000000000
```

As regex the separator would be `[,;:=\s]+`

**Comment by AndreaScorza** [comment]
Perfect, implemented it, before closing the issue,
i assume that the transfers are in multiple lines as was in the readMe like:

echo 'recipient1 amount1
recipient2 amount2' | lto mass-transfer

is that correct ?
